### ISSUE TITLE
Whatsapp media templates not included in typescript HSMContentContent interface

### ISSUE THREAD

**Issue by marcellox98** [messagebird/messagebird-nodejs#82]
Hello,

We are implementing media template in our project. But when I tried to add a `components` property to a `HSMContentContent` interface like is described in your [documentation](https://developers.messagebird.com/api/conversations/#hsmcontent) it gives a typescript error.

On closer inspection I noticed that there is indeed indeed no `components` property in the `HSMContentContent`. 
When I disable the typescript error the message does send like you expect.

**Comment by aodinok** [comment]
Hey, @marcellox98, 
I just created MR, can you please check if it has all fields that you want to use?
Also do not hesitate to create MR next time if you see something wrong.

**Comment by marcellox98** [comment]
Hi @aodinok,
I saw you forgot to add the `HSMComponentDocumentParameter` and `HSMComponentImageParameter` to the `HSMComponentParameter`.
Also when I tested it locally I got a typescript error in the normal template code since components should not be mandatory there.

I tried to add an MR with the fixes but is was not authorized

**Comment by aodinok** [comment]
Thanks for noticing this, I pushed a fix, can you please try again?

By the way, you should be able to fork repo and create PR from there.

**Comment by marcellox98** [comment]
I totally forgot i needed to make a PR...
There was still an issue that the `params` property was still mandatory inside the interface which will result in this error _"api error(s): Content is not valid for type hsm: hsm params and components can not be set at the same time (code: 21)"_ when sending a media template

I created a PR that fixes this: https://github.com/messagebird/messagebird-nodejs/pull/84
